# Домашнее задание "Линейная алгебра. Матрицы".

## Уровень 0:


### Задание 1

 - Создайте матрицу 3 на 3, заполненную числами от 1 до 9
 - Прибавьте к ней матрицу с единицами на диагонале
 - Умножьте полученную матрицу на вектор (1, 2, 3)
 - Вычислить транспонированную матрицу $A^T$ от полученной в результате прибавления матрицы
 - Посчитайте обратную матрицу к полученной в результате прибавления матрице


In [12]:
#импортируем нужные для работы пакеты
import numpy as np

#создаем телефонную матрицу
mx1 = np.array([[1,2,3], [4,5,6], [7,8,9]])

#создаем единичную матрицу
mx2 = np.eye(3)

#сложим две матрицы
mx3 = mx1 + mx2
mx3

array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

In [13]:
#умножим результат на вектор (1,2,3)
v = np.array([1,2,3])
mx4 = mx3*v
mx4

array([[ 2.,  4.,  9.],
       [ 4., 12., 18.],
       [ 7., 16., 30.]])

In [14]:
#вычислим транспонированную матрицу к mx3
mx5 = np.transpose(mx3)
mx5

array([[ 2.,  4.,  7.],
       [ 2.,  6.,  8.],
       [ 3.,  6., 10.]])

In [15]:
#вычислим обратную матрицу к mx3
mx6 = np.linalg.inv(mx3)
mx6

array([[-6.00000000e+00, -2.00000000e+00,  3.00000000e+00],
       [-1.00000000e+00,  5.00000000e-01, -2.33146835e-16],
       [ 5.00000000e+00,  1.00000000e+00, -2.00000000e+00]])

## Уровень 1:

### Задание 2

Найдите собственные значения и собственные вектора матрицы:
```
m = np.array([[2, 2],
              [1, 3]])
print(m)
```



In [ ]:
### YOUR CODE HERE

### Задание 3


Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

P.S. Матрица должна быть ненулевой и размерностью не менее 2!

In [ ]:
### YOUR CODE HERE