# Домашнее задание "Линейная алгебра. Матрицы".

## Уровень 0:


### Задание 1

 - Создайте матрицу 3 на 3, заполненную числами от 1 до 9
 - Прибавьте к ней матрицу с единицами на диагонале
 - Умножьте полученную матрицу на вектор (1, 2, 3)
 - Вычислить транспонированную матрицу $A^T$ от полученной в результате прибавления матрицы
 - Посчитайте обратную матрицу к полученной в результате прибавления матрице


In [1]:
#импортируем нужные для работы пакеты
import numpy as np

#создаем телефонную матрицу
mx1 = np.array([[1,2,3], [4,5,6], [7,8,9]])

#создаем единичную матрицу
mx2 = np.eye(3)

#сложим две матрицы
mx3 = mx1 + mx2
mx3

array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

In [2]:
#умножим результат на вектор (1,2,3)
v = np.array([1,2,3])
mx4 = mx3*v
mx4

array([[ 2.,  4.,  9.],
       [ 4., 12., 18.],
       [ 7., 16., 30.]])

In [3]:
#вычислим транспонированную матрицу к mx3
mx5 = np.transpose(mx3)
mx5

array([[ 2.,  4.,  7.],
       [ 2.,  6.,  8.],
       [ 3.,  6., 10.]])

In [4]:
#вычислим обратную матрицу к mx3
mx6 = np.linalg.inv(mx3)
mx6

array([[-6.00000000e+00, -2.00000000e+00,  3.00000000e+00],
       [-1.00000000e+00,  5.00000000e-01, -2.33146835e-16],
       [ 5.00000000e+00,  1.00000000e+00, -2.00000000e+00]])

In [5]:
#проверим обратную матрицу
mx7 = mx6@mx3
mx7

array([[ 1.00000000e+00,  0.00000000e+00,  3.55271368e-15],
       [-7.77156117e-17,  1.00000000e+00,  1.11022302e-16],
       [ 6.66133815e-16,  0.00000000e+00,  1.00000000e+00]])

## Уровень 1:

### Задание 2

Найдите собственные значения и собственные вектора матрицы:
```
m = np.array([[2, 2],
              [1, 3]])
print(m)
```



In [6]:
#импортируем нужные для работы пакеты
import numpy as np

#зададим матрицу m
m = np.array([[2, 2], [1, 3]])
m

array([[2, 2],
       [1, 3]])

In [7]:
#найдем собственные значения матрицы m
np.linalg.eigvals(m)

array([1., 4.])

In [9]:
#найдем собственные вектора матрицы m
e_vec = np.linalg.eig(m)[1]

array([[-0.89442719, -0.70710678],
       [ 0.4472136 , -0.70710678]])

In [14]:
#транспонируем матрицу собственных векторов для удобства преобразования
res1 = np.transpose(e_vec)

array([-0.89442719,  0.4472136 ])

In [17]:
#первый "красивый" собственный вектор
res2 = res1[0]/-0.4472136
res2

array([ 1.99999998, -0.99999999])

In [16]:
#второй "красивый" собственный вектор
res3 = res1[1]/-0.70710678
res3

array([1., 1.])

### Задание 3


Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

P.S. Матрица должна быть ненулевой и размерностью не менее 2!

In [7]:
#импортируем нужные для работы пакеты
import numpy as np

#возьмем матрицу 2х2, в которой произвольным образом зададим (2х2-1) = 3 элемента
elmts = np.random.randn(3)
elmts

array([0.92833765, 0.25753883, 1.06639283])

In [8]:
#вычислим последнее значение
elmt = (elmts[0] * elmts[1] + 1) / elmts[2]
elmt

1.1619385941666587

In [9]:
#соберем матрицу
mtrx = np.array([[elmt, elmts[0]],[elmts[1],elmts[2]]])
mtrx

array([[1.16193859, 0.92833765],
       [0.25753883, 1.06639283]])

In [10]:
#проверим что определитель равен 1
det_mtrx = np.linalg.det(mtrx)
det_mtrx

1.0